feat(auth): Will emit user status after register
digithun/jamplay-nap pull request #21
Opened 2018-02-19 05:09 UTC by katopz

2018-02-21 07:32 UTC, zapkub requested changes

2018-02-21 07:32 UTC, zapkub commented on server/nap.js
> +    this.emitter = new Mitt()
event emitter ถูกสร้างใหม่ทุกๆ request ต้องแก้เป็นทุก request ใช้ bus เดียวกัน

2018-02-23 10:32 UTC, ArtNattapat commented on server/authen-sessions.js
> +      if (!email) {
อันนี้ต้องเป็น emailVerifiedAt ด้วยรึเปล่า

2018-02-23 11:11 UTC, ArtNattapat approved these changes
pass

2018-02-23 11:38 UTC, merged